[package]
name = "life"
version = "0.1.0"
authors = ["Benoit LEGER <benoit.leger@hotmail.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.13"